// examples/react-router/app/routes/login.tsx
import { Form, data, redirect } from 'react-router';
import { safeRedirectPath } from '@better-iam/react-router';
import { demo, iamRouter } from '../iam.server';
import type { Route } from './+types/login';

// The in-process client signs in; the root middleware puts the session cookie on the redirect.
export async function action(args: Route.ActionArgs) {
  const form = await args.request.formData();
  const email = String(form.get('email') ?? '');
  let result;
  try {
    result = await iamRouter.helpers(args).client.auth.signIn({
      tenantId: demo.tenantId ?? String(form.get('tenantId') ?? ''),
      email,
      password: String(form.get('password') ?? ''),
    });
  } catch (error) {
    return data(
      { email, message: error instanceof Error ? error.message : 'Sign-in failed' },
      { status: 400 },
    );
  }
  if (!('token' in result))
    return data({ email, message: 'This demo does not handle MFA' }, { status: 400 });
  throw redirect(safeRedirectPath(new URL(args.request.url).searchParams.get('next')));
}

export default function Login({ actionData }: Route.ComponentProps) {
  return (
    <>
      <h1>Sign in</h1>
      <Form method="post">
        <label>
          Email{' '}
          <input
            name="email"
            type="email"
            autoComplete="username"
            defaultValue={actionData?.email}
          />
        </label>
        <label>
          Password <input name="password" type="password" autoComplete="current-password" />
        </label>
        <button>Sign in</button>
      </Form>
      {actionData?.message ? <p id="login-error">{actionData.message}</p> : null}
    </>
  );
}

// examples/nuxt/app/pages/login.vue
<script setup lang="ts">
const route = useRoute();
const client = useIamClient();
const { setSession } = useIamSession();
const { data: demo } = await useFetch('/api/demo');
const email = ref('member@example.test');
const password = ref('');
const error = ref('');

async function submit() {
  error.value = '';
  try {
    const result = await client.auth.signIn({
      tenantId: demo.value?.tenantId ?? '',
      email: email.value,
      password: password.value,
    });
    if (!('token' in result)) {
      error.value = 'This account needs a second factor; finish it with client.auth.verifyMfa.';
      return;
    }
    setSession(await client.auth.getSession());
    await navigateTo(typeof route.query.next === 'string' ? route.query.next : '/');
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : String(failure);
  }
}
</script>

<template>
  <main>
    <h1>Sign in</h1>
    <form @submit.prevent="submit">
      <label>Email <input v-model="email" type="email" autocomplete="username" /></label>
      <label>
        Password <input v-model="password" type="password" autocomplete="current-password" />
      </label>
      <button type="submit">Sign in</button>
      <p v-if="error" role="alert">{{ error }}</p>
    </form>
  </main>
</template>
